export async function onRequestPost(context) {
    try {
        const { request, env } = context;
        const data = await request.json();

        // Unique Invoice ID is generated by the client, but we verify or log it here
        const invoiceId = data.invoiceId || `GY-${Date.now()}`;

        // Discord Webhook for Transaction Logging
        const INVOICE_WEBHOOK = env.DISCORD_INVOICE_WEBHOOK;
        if (!INVOICE_WEBHOOK) {
            console.error("DISCORD_INVOICE_WEBHOOK is not defined in environment variables");
        }
        const discordPayload = {
            embeds: [{
                title: "🧾 New Invoice Summary Request",
                color: 15158332, // Pink
                fields: [
                    { name: "Invoice ID", value: invoiceId, inline: true },
                    { name: "Product", value: data.product || "N/A", inline: true },
                    { name: "Price", value: data.price || "N/A", inline: true },
                    { name: "Email", value: data.email || "N/A", inline: false },
                    { name: "Organisation", value: data.organisation ? `${data.organisation.name || 'N/A'}\nReg: ${data.organisation.reg || 'N/A'}\nCountry: ${data.organisation.country || 'N/A'}\nWeb: ${data.organisation.web || 'N/A'}` : "N/A", inline: false },
                    { name: "Language", value: data.language || "N/A", inline: true },
                    { name: "Subscribed", value: data.subscribe ? "✅ Yes" : "❌ No", inline: true }
                ],
                timestamp: new Date().toISOString()
            }]
        };

        // 1. Log to Discord
        if (INVOICE_WEBHOOK) {
            await fetch(INVOICE_WEBHOOK, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(discordPayload)
            });
        }

        const taglines = {
            'en': "Estonia's leading yoga and wellness studio",
            'et': "Eesti juhtiv jooga- ja heaolustuudio",
            'fi': "Viron johtava jooga- ja hyvinvointistudio",
            'ru': "Ведущая студия йоги и велнеса в Эстонии"
        };
        const tagline = taglines[data.language] || taglines['en'];

        // 2. Prepare Email HTML
        const emailHtml = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <style>
                    body { font-family: sans-serif; font-size: 18px; line-height: 1.6; color: #374151; margin: 0; padding: 0; background-color: #f9fafb; }
                    .container { max-width: 600px; margin: 40px auto; background: white; border-radius: 16px; overflow: hidden; border: 1px solid #f3f4f6; }
                    .header { background: #db2777; padding: 40px 20px; text-align: center; color: white; }
                    .content { padding: 40px; }
                    .invoice-card { background: #fdf2f8; border: 1px solid #fce7f3; border-radius: 12px; padding: 24px; margin-bottom: 32px; font-size: 18px; }
                    .invoice-no { font-size: 14px; text-transform: uppercase; letter-spacing: 0.1em; color: #be185d; font-weight: bold; }
                    .invoice-id { font-size: 18px; font-weight: bold; margin-bottom: 20px; }
                    .item-row { display: flex; justify-content: space-between; border-bottom: 1px solid #fce7f3; padding: 16px 0; }
                    .total-row { display: flex; justify-content: space-between; padding: 20px 0 0; font-weight: bold; font-size: 20px; }
                    .button { display: block; text-align: center; background: #db2777; color: white !important; text-decoration: none; padding: 16px; border-radius: 12px; font-weight: bold; text-transform: uppercase; }
                    .footer { padding: 40px; background: #f9fafb; text-align: center; font-size: 16px; color: #9ca3af; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1 style="margin-bottom: 8px;">GOYOGA ESTONIA</h1>
                        <p style="margin: 0; font-size: 16px; color: #fce7f3;">${tagline}</p>
                    </div>
                    <div class="content">
                        <h2>Order Summary</h2>
                        <p><strong>Thank you for your purchase with Goyoga Estonia!</strong> Below is your purchase summary.</p>
                        <div class="invoice-card">
                            <div class="invoice-no">Invoice No.</div>
                            <div class="invoice-id">${invoiceId}</div>
                            ${data.organisation ? `<div class="item-row"><span>Organisation</span><span style="text-align: right; word-break: break-all;">
                                <strong>${data.organisation.name || ''}</strong><br/>
                                ${data.organisation.reg ? 'Reg: ' + data.organisation.reg + '<br/>' : ''}
                                ${data.organisation.country || ''}
                            </span></div>` : ''}
                            <div class="item-row"><span>${data.product}</span><span>${data.price}</span></div>
                            <div class="total-row"><span>Total</span><span style="color: #db2777; font-size: 20px;">${data.price}</span></div>
                        </div>
                        
                        ${data.desc ? `
                        <div style="background: #fdf8fa; border: 1px solid #fce7f3; border-radius: 8px; padding: 20px; margin-bottom: 24px; font-size: 14px; color: #db2777;">
                            <strong style="display: block; margin-bottom: 8px; text-transform: uppercase;">Terms & Validity:</strong>
                            ${data.desc}
                        </div>
                        ` : ''}
                        
                        <p style="font-size: 14px; text-align: center; margin-bottom: 24px;">Complete your transaction on the website or via the link in your account.</p>
                        <p style="text-align: center; font-size: 14px;"><em>This is an automated summary. Final receipt will be issued upon payment.</em></p>
                        ${data.subscribe ? `
                        <p style="text-align: center; font-size: 16px; font-weight: bold; margin-top: 32px; color: #db2777;">
                            Thank you for subscribing to our community!
                        </p>
                        ` : ''}
                    </div>
                    <div class="footer">
                        <p><strong>Goyoga Estonia OU</strong><br/>Narva mnt 7D, Tallinn</p>
                        <p>Website: <a href="https://www.goyoga.ee" style="color: #db2777; text-decoration: none;">www.goyoga.ee</a></p>
                        <p>Contact: <a href="mailto:info@goyoga.ee" style="color: #db2777; text-decoration: none;">info@goyoga.ee</a></p>
                        ${data.subscribe ? `<p style="margin-top: 24px;"><a href="mailto:info@goyoga.ee?subject=Unsubscribe" style="color: #9ca3af; text-decoration: underline;">Click here to unsubscribe</a></p>` : ''}
                    </div>
                </div>
            </body>
            </html>
        `;

        // 3. Send via Zoho ZeptoMail
        const ZOHO_KEY = env.ZOHO_API_KEY;
        if (!ZOHO_KEY) {
            console.error("ZOHO_API_KEY is not defined in environment variables");
            return new Response(JSON.stringify({ success: false, error: "Missing Email Configuration" }), { status: 500 });
        }
        try {
            const zeptoResponse = await fetch("https://api.zeptomail.eu/v1.1/email", {
                method: "POST",
                headers: {
                    "accept": "application/json",
                    "content-type": "application/json",
                    "authorization": ZOHO_KEY
                },
                body: JSON.stringify({
                    "from": { "address": "online.services@goyoga-billing.cc", "name": "Goyoga Services" },
                    "to": [
                        { "email_address": { "address": data.email, "name": "Customer" } },
                        { "email_address": { "address": "info@goyoga.ee", "name": "Goyoga Tracker" } },
                        { "email_address": { "address": "online.services@goyoga-billing.cc", "name": "Goyoga Billing Archive" } },
                        { "email_address": { "address": "arved@goyoga.ee", "name": "Goyoga Accounting" } }
                    ],
                    "subject": `Goyoga Estonia Purchase Summary - ${invoiceId}`,
                    "htmlbody": emailHtml
                })
            });
            
            const zeptoData = await zeptoResponse.json();
            console.log("ZeptoMail Response:", zeptoData);
            if (!zeptoResponse.ok) {
                console.error("ZeptoMail error details:", zeptoData);
            }
        } catch (e) {
            console.error("ZeptoMail Error:", e);
        }

        return new Response(JSON.stringify({ 
            success: true, 
            invoiceId: invoiceId 
        }), {
            status: 200,
            headers: { "Content-Type": "application/json" }
        });

    } catch (error) {
        return new Response(JSON.stringify({ success: false, error: error.message }), {
            status: 500,
            headers: { "Content-Type": "application/json" }
        });
    }
}
