export async function onRequestPost(context) {
    try {
        const { request, env } = context;
        const data = await request.json();

        // Unique Invoice ID is generated by the client, but we verify or log it here
        const invoiceId = data.invoiceId || `GY-${Date.now()}`;

        // Discord Webhook for Transaction Logging
        const INVOICE_WEBHOOK = env.DISCORD_INVOICE_WEBHOOK || "https://discordapp.com/api/webhooks/1478382833251913821/KT2rKdgAndFhmGFdSrasbhUI1Ada49UVIa7kLB2ONlOg08f3HSXMk9SjHJ3pAu6Aox-G";

        const discordPayload = {
            embeds: [{
                title: "🧾 New Invoice Summary Request",
                color: 15158332, // Pink
                fields: [
                    { name: "Invoice ID", value: invoiceId, inline: true },
                    { name: "Product", value: data.product || "N/A", inline: true },
                    { name: "Price", value: data.price || "N/A", inline: true },
                    { name: "Email", value: data.email || "N/A", inline: false },
                    { name: "Language", value: data.language || "N/A", inline: true },
                    { name: "Subscribed", value: data.subscribe ? "✅ Yes" : "❌ No", inline: true }
                ],
                timestamp: new Date().toISOString()
            }]
        };

        // 1. Log to Discord
        await fetch(INVOICE_WEBHOOK, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(discordPayload)
        });

        // 2. Prepare Email HTML
        const emailHtml = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <style>
                    body { font-family: sans-serif; line-height: 1.6; color: #374151; margin: 0; padding: 0; background-color: #f9fafb; }
                    .container { max-width: 600px; margin: 40px auto; background: white; border-radius: 16px; overflow: hidden; border: 1px solid #f3f4f6; }
                    .header { background: #db2777; padding: 40px 20px; text-align: center; color: white; }
                    .content { padding: 40px; }
                    .invoice-card { background: #fdf2f8; border: 1px solid #fce7f3; border-radius: 12px; padding: 24px; margin-bottom: 32px; }
                    .invoice-no { font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #be185d; font-weight: bold; }
                    .invoice-id { font-size: 14px; font-weight: bold; margin-bottom: 20px; }
                    .item-row { display: flex; justify-content: space-between; border-bottom: 1px solid #fce7f3; padding: 12px 0; }
                    .total-row { display: flex; justify-content: space-between; padding: 16px 0 0; font-weight: bold; }
                    .button { display: block; text-align: center; background: #db2777; color: white !important; text-decoration: none; padding: 16px; border-radius: 12px; font-weight: bold; text-transform: uppercase; }
                    .footer { padding: 40px; background: #f9fafb; text-align: center; font-size: 11px; color: #9ca3af; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header"><h1>GOYOGA TALLINN</h1></div>
                    <div class="content">
                        <h2>Order Summary</h2>
                        <p>Thank you for choosing GoYoga. Below is your purchase summary.</p>
                        <div class="invoice-card">
                            <div class="invoice-no">Invoice No.</div>
                            <div class="invoice-id">${invoiceId}</div>
                            <div class="item-row"><span>${data.product}</span><span>${data.price}</span></div>
                            <div class="total-row"><span>Total</span><span style="color: #db2777; font-size: 20px;">${data.price}</span></div>
                        </div>
                        
                        ${data.desc ? `
                        <div style="background: #fdf8fa; border: 1px solid #fce7f3; border-radius: 8px; padding: 16px; margin-bottom: 24px; font-size: 11px; color: #db2777;">
                            <strong style="display: block; margin-bottom: 8px; text-transform: uppercase;">Terms & Validity:</strong>
                            ${data.desc}
                        </div>
                        ` : ''}
                        
                        <p style="font-size: 12px; text-align: center; margin-bottom: 24px;">Complete your transaction on the website or via the link in your account.</p>
                        <p style="text-align: center;"><em>This is an automated summary. Final receipt will be issued upon payment.</em></p>
                    </div>
                    <div class="footer">
                        <p>GoYoga Tallinn | Narva mnt 7D, Tallinn</p>
                        <p>Contact: online.services@goyoga-billing.cc</p>
                    </div>
                </div>
            </body>
            </html>
        `;

        // 3. Send via Zoho ZeptoMail
        // NOTE: It is recommended to move this token to Cloudflare Environment Variables (ZOHO_API_KEY) for better security.
        const ZOHO_KEY = env.ZOHO_API_KEY || "Zoho-enczapikey yA6KbHsIvQn3yz5TQxJp0pCOoY9krf9vj3jksyHhe5d0e4GyiqFs3xVudNO/IDuJ3YHY46ICatNCdIHv6twKe5diZoVYKJTGTuv4P2uV48xh8ciEYNYhjJirA7IUFqVIeRotCSw1Q/MoWA==";

        try {
            const zeptoResponse = await fetch("https://api.zeptomail.eu/v1.1/email", {
                method: "POST",
                headers: {
                    "accept": "application/json",
                    "content-type": "application/json",
                    "authorization": ZOHO_KEY
                },
                body: JSON.stringify({
                    "from": { "address": "online.services@goyoga-billing.cc", "name": "GoYoga Billing" },
                    "to": [
                        { "email_address": { "address": data.email, "name": "Customer" } },
                        { "email_address": { "address": "info@goyoga.ee", "name": "GoYoga Tracker" } },
                        { "email_address": { "address": "online.services@goyoga-billing.cc", "name": "GoYoga Billing Archive" } },
                        { "email_address": { "address": "arved@goyoga.ee", "name": "GoYoga Accounting" } }
                    ],
                    "subject": `GoYoga Purchase Summary - ${invoiceId}`,
                    "htmlbody": emailHtml
                })
            });
            
            const zeptoData = await zeptoResponse.json();
            console.log("ZeptoMail Response:", zeptoData);
            if (!zeptoResponse.ok) {
                console.error("ZeptoMail error details:", zeptoData);
            }
        } catch (e) {
            console.error("ZeptoMail Error:", e);
        }

        return new Response(JSON.stringify({ 
            success: true, 
            invoiceId: invoiceId 
        }), {
            status: 200,
            headers: { "Content-Type": "application/json" }
        });

    } catch (error) {
        return new Response(JSON.stringify({ success: false, error: error.message }), {
            status: 500,
            headers: { "Content-Type": "application/json" }
        });
    }
}
